In [1]:
#we have to import the data set to the colab note book
import pandas as pd #pd is a nick name throught the code we call the pandas as pd
df=pd.read_csv('data.csp.csv')#df is a variable,__csv is a predefined function from pandas pacakage

In [2]:
type(df)

pandas.core.frame.DataFrame

In [3]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
#step2 : grouping the input colums out put colums
X=df.iloc[:,:3]

# New Section

In [5]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [6]:
Y=df.iloc[:,3:4]

In [7]:
Y

Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

In [8]:
#convert input and output date into array format
X=X.values

In [9]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
Y=Y.values

In [11]:
Y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [12]:
#handling missing data or cleaning data
#step3 handing missing data and NaN values
#scenario1 : missing values in numerical column
#scenario 2: fill the empty value in highly repeated values
#scenario3: removing data set from 2 rows

import numpy as np
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [13]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
np.remainder='passthrough'
X=ct.fit_transform(X)

In [15]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [16]:
#onehotencoder is only usefull for input column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [17]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [18]:
# step 5 :slipt the data in to training and testing data.
from sklearn. model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [19]:
X_train

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object)

In [20]:
X_test

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 48.0, 79000.0]], dtype=object)

In [21]:
Y_train

array([1, 0, 0, 0, 0, 1, 0, 1])

In [22]:
Y_test

array([1, 1])

In [23]:
#step6:feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [24]:
X_train

array([[1.0, 0.0, 0.0, -0.36187533579795855, -0.3569354144614659],
       [1.0, 0.0, 0.0, 0.9555135271069697, 0.9326376958509272],
       [0.0, 1.0, 0.0, -1.0937580374118077, -0.7253848745507211],
       [0.0, 1.0, 0.0, 1.8337727690435885, 1.9458737110963789],
       [0.0, 0.0, 1.0, 0.07725428517035085, -0.08059831939452457],
       [1.0, 0.0, 0.0, -0.06912225515241896, 0.4720758707393582],
       [0.0, 0.0, 1.0, 0.19110270542139415, -0.9096096045953487],
       [0.0, 0.0, 1.0, -1.532887658380117, -1.278059064684604]],
      dtype=object)

In [25]:
X_test

array([[0.0, 1.0, 0.0, 0.37000736581589044, 0.17526936122301404],
       [1.0, 0.0, 0.0, 1.541019688398049, 1.5774242510071237]],
      dtype=object)

In [26]:
#machine learning
#types in machine learning
#unsuperwised learning:here we have unlabeled data,model remembers the pattern
#superwised learning:we have a labeled data ,and the model the model tasks are classified or prediction
#rainforcement learning:model will learn from failures


In [28]:
#logistic regression alogarithm
#linear regression alogarithm
#step7=training alogarithm applied to the dataset for model training
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)


LogisticRegression()

In [29]:
Y_pred=classifier.predict(X_test)

In [30]:
Y_pred

array([0, 0])